### ISSUE TITLE
Usage of luajit instead of lua

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib-lua#5]
Why not use luajit instead of lua ?

**Comment by raysan5** [comment]
Sorry, I'm not an expert on LuaJIT, never used it, is it similar to Lua in usage? I understand is a Lua compiler with big performance improvement...

**Comment by raysan5** [comment]
Here it is a quick implementation of [raylib-lua-ffi](https://gist.github.com/alexander-matz/f8ee4eb9fdf676203d70c1e5e329a6ec).
